CREATE TABLE IF NOT EXISTS financial_health_state (
    user_id INT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    grade VARCHAR(32) NOT NULL,
    score NUMERIC(5, 2),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
